spring:
  application:
    name: friendsnet
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    url: jdbc:h2:~/db_friendsnet;DB_CLOSE_DELAY=1000
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework: INFO
server:
  port: 8080